### ISSUE TITLE
iSense sleep mode and UART communication

### ISSUE THREAD

**Issue by GDanii** [ibr-alg/wiselib#36]
Hi,

I discovered that the sleep mode which was added to the repository on 4th of February, terminates the UART communication towards the node. If I change the true to false in the insense_os_standalone.cpp:

os.allow_sleep( false ); //WISELIB_ALLOW_SLEEP );
os.allow_doze( false ); //WISELIB_ALLOW_DOZE );

Then it is working, but when it is true, the node doesn't receive the UART message, the sending part is okay. I tried it in the Wisebed with the uart test application.

**Comment by Droggelbecher** [comment]
Hi GDanii, nice find.
Could you re-insert the WISELIB_ALLOW_SLEEP & WISELIB_ALLOW_DOZE flags (instead of hardwired true/false), make them default to true but settable by the application programmer?
You can find an example when looking at the WISELIB_EXIT_MAIN variable used in Makefile.pc.
And if that works, do a pull request?

If you can, thanks a lot in advance. If not, I'll do it, but expect a few days delay..

**Comment by GDanii** [comment]
Hi,
Actually there are no free nodes in the testbed today... so I cannot try it now. I'm not familiar with this sleeping part, how does it work and what is the real problem but isn't there a better solution? I mean that if it is settable by the programmer it will still cause the problem with the UART communication if it is enabled.

**Comment by Droggelbecher** [comment]
The user/application programmer does not necessarily _want_ UART communication (e.g. the nodes might not be installed in a testbed).
But as its true that this might come unexpected, the default behavior should surely be no sleep and working UART.
As already discussed via email: I'll care for the testbed ASAP, currently I'm travelling and cant access it from here. Can you work with a different testbed (eg. UZL) for the time being?
