### ISSUE TITLE
Defect in map in operator++

### ISSUE THREAD

**Issue by gitbaum** [ibr-alg/wiselib#4]
when calling map[key]++ (with int values in the map), the value is not incremented. is this a defect? does this really happen?

Check again!

**Comment by Droggelbecher** [comment]
which map does this refer to? map_list or map_static_vector?

**Comment by gitbaum** [comment]
afaik that happened in the map_static_vector

**Comment by shubhamsomani** [comment]
I checked out this issue and tried post increment operator on map_static_vector. It works fine for me.
Please see http://www.flickr.com/photos/93013264@N03/8454486177/in/photostream for details.

**Comment by Droggelbecher** [comment]
Thanks shubhamsomani for testing.
I'm closing this as I know of nobody who can reproduce this, also since the opening of this bug there
where commits affecting operator[], so it might have been fixed as a side-effect meanwhile.

If somebody encounters this (or another) problem, dont hesitate to open a new issue.
